apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: test-namespace
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 1Gi
